services:
  db:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chill_admin
      - MONGO_INITDB_ROOT_PASSWORD=chill_admin_pwd
    volumes:
      - ./db_scipts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
  redis:
    image: redis:latest
    container_name: redis_cont
    ports: 
      - 6379:6379
    restart: always
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: celery_worker_container
    depends_on:
      - redis
    command: ["poetry", "run", "celery", "-A", "app.celery_config", "worker", "-l", "info", "-B"]
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_bot_container
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "mongodb://chill_user:chill_user_pwd@db:27017/schedule"
    ports:
      - "8502:8502"
    command: ["sh", "-c", "sleep 10 && poetry run python app/bot.py"]
