FROM python:3.11-slim-bookworm

WORKDIR /app

RUN pip install --no-cache-dir celery pytz aiogram bson pymongo

COPY ./app /app
RUN adduser --disabled-password --disabled-login celery
USER celery

CMD ["celery", "-A", "celery_config", "worker", "-l", "info", "-B"]
