services:
  db:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "1234:1234"
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_bot_container
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mongodb://db:27017/mydatabase"
    ports:
      - "8502:8502"
    command: ["sh", "-c", "sleep 10 && poetry run python app/bot.py"]
  